language: python

python:
  - "2.7"

install:
  - pip install coveralls
  - pip install pylint
  - pip install pep8

script:
  - pylint --max-line-length=240 dns_ui_sdk
  - pep8 --max-line-length=120 dns_ui_sdk
  - coverage run --source dns_ui_sdk setup.py test

after_success:
  - coveralls
